# -*- coding: utf-8 -*-
"""Baitap1.5_Flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PGGA8BMVW6t50mj6sN8CR4qPr0zfA6py
"""
from flask import Flask, send_file
from PIL import Image
import numpy as np
import io
import matplotlib.pyplot as plt

app = Flask(__name__)

@app.route('/')
def index():
    # Open the grayscale image
    img = Image.open('bird.png').convert('L')
    # Convert image to ndarray
    im1 = np.asarray(img)
    # Finding the maximum and minimum pixel values
    b = im1.max()
    a = im1.min()
    # Converting img to float
    c = im1.astype(float)
    # Contrast stretching transformation
    im2 = 255 * (c - a) / (b - a)
    # Convert im2 from ndarray to image
    im3 = Image.fromarray(im2.astype(np.uint8))

    # Create a BytesIO object to store the image data
    img_buffer = io.BytesIO()
    # Save the image to the BytesIO object in PNG format
    im3.save(img_buffer, format='PNG')
    img_buffer.seek(0)

    return send_file(img_buffer, mimetype='image/png')

if __name__ == '__main__':
    app.run()