# -*- coding: utf-8 -*-
"""Lab2_1.3_Flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SM5kdnNXbe2RKRXSQOkmXcayyDJSHc8F
"""

from PIL import Image
import math
import scipy
import numpy as np
import matplotlib.pyplot as plt
from flask import Flask, render_template,send_file

app = Flask(__name__)

@app.route('/')
def home():
    img = Image.open('bird.png').convert('L')
    im_1 = np.asarray(img)

#convert ndarray from int to float
    b1 = im_1.astype(float)

#find maximum value in b1
    b2 = np.max(b1)

#performing the log transformation
    c = (128.0 * np.log(1 + b1))/np.log(1 + b2)

#c1 is converted type int
    c1 = c.astype(np.uint8)

    new_img = Image.fromarray(c1)
    temp_image_path = 'temp_image.png'
    new_img.save(temp_image_path)
    return render_template('index_1.3.html',image_path=temp_image_path)
@app.route('/image')
def get_image():
    # Send the saved image file
    return send_file('temp_image.png', mimetype='image/png')

if __name__ == '__main__':
    app.run()