# -*- coding: utf-8 -*-
"""LAB2_1.2_Flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZghlUT42zpjukmi5ccx0cUMebC9dMplv
"""

from PIL import Image
import math
import scipy
import numpy as np
import matplotlib.pyplot as plt
from flask import Flask, render_template,send_file

app = Flask(__name__)

@app.route('/')
def home():
    img = Image.open('bird.png').convert('L')

    im_1 = np.asarray(img)

    gamma = 5

    b1 = im_1.astype(float)
    b2 = np.max(b1)
    b3 = b1/b2
    b2 = np.log(b3) * gamma

    c = np.exp(b2) * 255.0

    c1 = c.astype(np.uint8)

    new_img = Image.fromarray(c1)

    temp_image_path = 'temp_image.png'
    new_img.save(temp_image_path)

    return render_template('index_1.2.html',image_path=temp_image_path)

@app.route('/image')
def get_image():
    # Send the saved image file
    return send_file('temp_image.png', mimetype='image/png')

if __name__ == '__main__':
    app.run()